import type { Metadata } from "next";
import { getPage, type PublicRoute } from "@/data/pages";
import { SITE_NAME, SITE_URL } from "@/data/site";

/**
 * Shared metadata helpers.
 *
 * Every route's title, description and Open Graph copy lives once in
 * `data/pages.ts`; this turns a registry entry into Next's `Metadata` object.
 * Because the sitemap, llms.txt and the JSON-LD read that same registry, a
 * page's description can never say one thing in `<meta>` and another in the
 * structured data.
 *
 * The card image is the PNG generated by `app/opengraph-image.tsx`, referenced
 * by its route path. Next only injects a file-convention image automatically
 * where a segment does not declare `openGraph` itself — and every route here
 * does, to carry its own title and description — so without this the image
 * would appear on "/" alone. Verified in the built HTML.
 *
 * This replaced `/og-image.svg`: Facebook, X, LinkedIn, WhatsApp and Slack do
 * not render SVG Open Graph images, so shares previously had no image at all.
 */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "RabbitPay - 1-Click Checkout, built in India",
};

export function pageMetadata(path: PublicRoute): Metadata {
  const page = getPage(path);
  return {
    title: page.title,
    description: page.description,
    alternates: { canonical: page.path },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: "en_IN",
      url: new URL(page.path, SITE_URL).toString(),
      title: page.ogTitle ?? page.title,
      description: page.description,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: page.ogTitle ?? page.title,
      description: page.description,
      images: [OG_IMAGE.url],
    },
  };
}
